# Generated by Django 5.0.2 on 2024-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_delete_dispositivos_remove_informe_infousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dispositivo', models.CharField(max_length=30, unique=True)),
                ('cantidad_dispositivo', models.PositiveIntegerField()),
                ('cantidad_consumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumo_horas', models.FloatField()),
            ],
        ),
    ]
