# Generated by Django 5.0.2 on 2024-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_dispositivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='consumo_horas',
            new_name='consumo_hora',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='cantidad_consumo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='cantidad_dispositivo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre_dispositivo',
            field=models.CharField(max_length=255),
        ),
    ]
