# Generated by Django 5.0.2 on 2024-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_consumo_horas_dispositivo_consumo_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='cantidad_dispositivo',
            field=models.FloatField(),
        ),
    ]
