# Generated by Django 5.0.2 on 2024-02-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_dispositivo_cantidad_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='total_energia',
            field=models.FloatField(default=0.0),
        ),
    ]
