# Generated by Django 5.0.2 on 2024-02-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_dispositivo_total_energia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
