# Generated by Django 5.0.2 on 2024-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_dispositivo_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
