# Generated by Django 5.0.2 on 2024-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_remove_dispositivo_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='api_google_maps',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='Valor predeterminado', max_length=255),
        ),
    ]
