# Generated by Django 5.0.2 on 2024-02-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_remove_usuario_api_google_maps_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nuevo_campo',
        ),
    ]
