# Generated by Django 5.0.2 on 2024-03-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default='valor_por_defecto'),
        ),
    ]
