# Generated by Django 5.0.2 on 2024-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_alter_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneracionEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_energia', models.CharField(choices=[('solar', 'Panel Solar'), ('eolico', 'Eólico')], max_length=10)),
                ('capacidad_generacion', models.FloatField(help_text='Capacidad de generación en kW')),
                ('ubicacion', models.CharField(help_text='Ubicación del generador', max_length=100)),
                ('fecha_instalacion', models.DateField(help_text='Fecha de instalación')),
            ],
        ),
    ]
