# Generated by Django 5.0.2 on 2024-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_generacionenergia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacionenergia',
            name='fecha_instalacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de instalación'),
        ),
    ]
