# Generated by Django 5.0.2 on 2024-03-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_alter_generacionenergia_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacionenergia',
            name='fecha_instalacion',
            field=models.DateTimeField(help_text='Fecha de instalación'),
        ),
    ]
