# Generated by Django 5.0.2 on 2024-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_alter_generacionenergia_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacionenergia',
            name='fecha_instalacion',
            field=models.DateField(help_text='Fecha de instalación'),
        ),
    ]
